### ISSUE TITLE
Not working in Ventura RC2 on MBP M1Max

### ISSUE THREAD

**Issue by intrepidsilence** [TheMurusTeam/PowerMetrix#1]
Helper is in place. Restarted app, still no go. Hppy to test and provide logs, etc, as guided.

**Comment by TheMurusTeam** [comment]
Hello Michael,

thank you for your help.
There are a bunch of things you can try to debug this issue:
1) Run PowerMetrix (better if using an admin user, from /Applications dir), and check if helper process (it.murus.powermetrix.helper) starts. You can use Activity monitor.
2) from the terminal, run these commands and tell me the output:
 - sudo launchctl list | grep it.murus
 - sudo launchctl print-disabled system | grep it.murus

Then, one more thing you can try is to quit PowerMetrix then run these shell commands and then run PowerMetrix again and see if something changes:
- sudo launchctl enable system/it.murus.powermetrix.helper
- sudo launchctl load /System/Library/LaunchDaemons/it.murus.powermetrix.helper.plist

Please let me know. thank you

Kind Regards,
hany



The Murus Team
- - - - - - - - - - - - - 
***@***.*** ***@***.***>
www.murusfirewall.com <http://www.murusfirewall.com/>
www.vallumfirewall.com <http://www.vallumfirewall.com/>

**Comment by intrepidsilence** [comment]
RC2 fixed the missing data and it is working now. Found another bug though. Will file another report.
